### ISSUE TITLE
Serious issue on purchaseUpdatedListener(). It gets all old transaction

### ISSUE THREAD

**Issue by hakkikonu** [dooboolab/react-native-iap#1139]
### Version of react-native-iap
4.6.3

### Version of react-native
0.63.3
### Platforms you faced the error (IOS or Android or both?)
IOS 14
### Expected behavior
Should trigger when an event occured
### Actual behavior
When page loaded, all old purchase triggered
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior

```
 purchaseUpdateSubscription = purchaseUpdatedListener(async (purchase) => {
      console.log('purchaseUpdatedListenerLOG', purchase);
}

```

It's really serious issue. In `purchaseUpdatedListener` function I make back-end requests. Now all purchases mixed. Need very fast solution.

All below purchases are from july 14. Why we're getting old transaction values?

![GitHub Logo](https://i.ibb.co/HpQbbWd/Screen-Shot-2020-10-01-at-16-03-01.png)

**Comment by hakkikonu** [comment]
@hyochan

**Comment by Trinnitty** [comment]
The same for me ((

**Comment by sdenaci** [comment]
This is also happening for me.

**Comment by Maddoc42** [comment]
We're having the same issue, with regular IAPs instead of subscriptions though. Backend is receiving seemingly random transactions.

Not sure if this is an `react-native-iap` issue though, as validation response from apple **also** show multiple transactions, some of them being older. In addition, these issues have started what looks like out of nowhere, with no code changes from our side.

Has anyone heard of this issue outside of RN?

**Comment by jeffelector** [comment]
same here

**Comment by hieutran24** [comment]
this is because the finishTransaction not work on iOS that's why all transaction is pending and u gets all of them next time u open app or purchase

**Comment by AdrianMrn** [comment]
Did any of you manage to fix this? `clearTransactionIOS()` doesn't seem to do it for me either.

**Comment by hyochan** [comment]
Looks like a dup #1138.
