### ISSUE TITLE
Purchase error code "E_UNKNOWN" with message: "Cannot connect to iTunes"

### ISSUE THREAD

**Issue by binhchili** [dooboolab/react-native-iap#1165]
### Steps to reproduce the behavior

All my code is same as the example. Test with my sandbox account.
![IMG_4298](https://user-images.githubusercontent.com/69777410/96688211-18b85100-13ab-11eb-8bfa-d3eac459dd85.PNG)
![IMG_EB17C0256776-1](https://user-images.githubusercontent.com/69777410/96688226-1d7d0500-13ab-11eb-9826-af8bcd18c58e.jpeg)

**Comment by traingethermarc** [comment]
Have you tried initConnection()?

**Comment by patrick-tresp** [comment]
i am running into same issue.

tried:
- use verified sandbox user
- use non-verified sandbox user ( E-Mail not verified )
- no sandbox user set and logging in within purchase process ( with either verified or non-verified user )

also using `initConnection()` which returns true in logs.

i can fetch the list of products and subscriptions from account, but neither requestPurchase nor requestSubscription

```
public async requestPurchase(sku: string) {
    console.warn('requestPurchase ', sku)
    const init = await RNIap.initConnection()
    console.log('InAppPurchase -> requestPurchase -> init', init)
    try {
      return await RNIap.requestPurchase(sku, false)
    } catch (err) {
      console.warn(err.code, err.message)
    }
  }

public async requestSubscription(sku: string) {
    console.log('InAppPurchase -> requestSubscription')
    const init = await RNIap.initConnection()
    console.log('InAppPurchase -> requestSubscription -> init', init)
    try {
      return await RNIap.requestSubscription(sku)
    } catch (err) {
      console.warn(err.code, err.message)
    }
  }
```

**Comment by traingethermarc** [comment]
Do you have a purchaseUpdatedListener with finishTransaction? @patrick-tresp

**Comment by patrick-tresp** [comment]
Hey thanks for fast repy @traingethermarc ,

i do run this when `componentDidMount`

```
RNIap.initConnection().then(() => {
      console.log('InAppPurchase -> initializePurchaseListener -> RNIap.initConnection().then()')
      // we make sure that "ghost" pending payment are removed
      // (ghost = failed pending payment that are still marked as pending in Google's native Vending module cache)
      RNIap.flushFailedPurchasesCachedAsPendingAndroid()
        .catch(() => {
          // exception can happen here if:
          // - there are pending purchases that are still pending (we can't consume a pending purchase)
          // in any case, you might not want to do anything special with the error
        })
        .then(() => {
          console.log('InAppPurchase -> RNIap.flushFailedPurchasesCachedAsPendingAndroid -> then')
         purchaseUpdateSubscription = purchaseUpdatedListener(
            (purchase: InAppPurchase | SubscriptionPurchase | ProductPurchase) => {
              console.log('GLOBAL purchaseUpdatedListener', JSON.stringify(purchase))
                  }) 
            },
          )
          console.log(
            'InAppPurchase -> initializePurchaseListener -> InAppPurchase.getInstance().purchaseUpdateSubscription',
            purchaseUpdateSubscription,
          )

          purchaseErrorSubscription = purchaseErrorListener(
            (error: PurchaseError) => {
              console.warn('purchase ErrorListener', error)
            },
          )
        })
    })
```

But only `purchaseErrorListener` is returning an Error, `purchaseUpdatedListener` has not returned anything so far.

**Comment by traingethermarc** [comment]
```
const getProductsIAP = useCallback(async () => {
  await clearProductsIOS();
  await clearTransactionIOS();

 try {
   const result = await initConnection();
   const products = await getProducts(itemSkus);
   props.setProducts(products);
   console.log('result', result);
 } catch (err) {
   console.warn(err.code, err.message);
 }

  purchaseUpdateSubscription = purchaseUpdatedListener(
    async (purchase) => {
      const receipt = purchase.transactionReceipt;
      console.log('purchaseUpdatedListener');
      if (receipt) {
        try {
          await processNewPurchase(purchase); //your backend call
        } catch (ackErr) {
           console.log('ackErr', ackErr);
        }
      } else {
        console.log('purchaseUpdatedListener error: receipt');
      }
    },
  );

  purchaseErrorSubscription = purchaseErrorListener(
    (error: PurchaseError) => {
      console.log('purchaseErrorListener', error);
      console.log(JSON.stringify(error));
    },
  );
}, []);
```

I am using hooks but this could be easily converted to componentDidMount.

**Comment by traingethermarc** [comment]
I had the same problem - I assume you test on a real device which is not updated to IOS 14 already? If this is the case update it to IOS 14 or upload the project to TestFlight. It´s a problem on Apple´s side: https://developer.apple.com/forums/thread/98763

**Comment by patrick-tresp** [comment]
@traingethermarc 

you assume right! i will update test-device immediately and come back to you!
thanks so far!

**Comment by 106firestarter** [comment]
I have various devices on different OS versions and I have this problem on each one of them. I've contacted Apple in regards to this and we're still following up the case, however, without any solid conclusions. I do not believe it is a problem with the package, it must be something on the Apple's side. I've tried everything people are mentioning on this thread and in other threads that have reported a similar problem. The In App Purchase dialog is just inconsistent on showing up and until now, I cannot find a valid reason for it because the outcome are always different. Sometimes I get an E_UNKNOWN error, other times I get zero feedback, sometimes the pop up shows after 10 mins of waiting and other times it just works... I've tried with sandbox users, non sandbox users, I've had the same different outcomes for the same user and device and not even an error or a conclusive/insightful log is shown. This is just frustrating to debug because you can't find pretty much anything... Well, if you guys have any sort of advice or insight, I'm listening ... In the meantime, if I have some news from Apple, I'll keep you posted...

**Comment by traingethermarc** [comment]
Yes the package is definitely kind of buggy sometimes... :( hopefully they will fix it someday, because there is no real alternative out there. Only can give you the tipps with IOS 14, TestFlight and a "proper" use of the API (which is hard, because there is no real implementation, which is working 100% - as far as I can tell after maaaaaany hours of working with it and by reading different issues here...)

**Comment by patrick-tresp** [comment]
@traingethermarc 
as promised:
- after installing iOS 14 on Device
- after installing XCode 12.1 ( otherwise device was always lost )

I get a successful payment in sandbox with purchase response containing

- productId, 
- transactionDate, 
- transactionId and 
- transactionReceipt

Thanks so much, i would have still be looking into code and try to debug.

**Comment by jkz27** [comment]
Are you guys able to call finishTransaction on the IOS side? And I have the same issue, its likely the apple side issue and IOS 14 does resolve it which I can confirm

**Comment by binhchili** [comment]
@traingethermarc thanks to your guide I  upgraded my device to IOS 14 and it worked. But can I ask you one more question. I try to log the object from `transactionReceipt` method and it show me a very long encrypted string. It's very different from the payload I receive on Android which is a clearly JSON object. So how can I know a purchase in IOS is successful ?

**Comment by traingethermarc** [comment]
Yes @binhchili in order to verify the receipt you have to send it to your backend. You can use `'node-apple-receipt-verify'` and once you validated it you can see the product which was purchased. Then you can store it in your database and send a `"success"` to your client in order to `finishTransaction`.

**Comment by jkz27** [comment]
Hey @traingethermarc, don't we need to manually call finish transaction on IOS side? I have validated my receipt from apple side through my server, but I am unable to finish the transaction by calling finishtransaction, it is returning undefined.

**Comment by traingethermarc** [comment]
I am sending "success" back from server and once the client recieves it:  `await finishTransaction(purchase); ` `finishTransaction` is working for both android and iOS. 
```

then(async (data) => {
        console.log(data);
        props.setProcessing(false);
        if (data.ack === 'success') {
          console.log('finished');
          await finishTransaction(purchase);
        //  props.setActivePlan({ planId: productId });
      }
```

**Comment by binhchili** [comment]
@traingethermarc I just log out the `purchase` object while testing on Android and find that there are 2 fields: `purchaseState` and `purchaseStateAndroid`.  `purchaseState` return 0 while `purchaseStateAndroid ` return 1. Can you explain the difference between 2 field ?

**Comment by hyochan** [comment]
> @traingethermarc I just log out the `purchase` object while testing on Android and find that there are 2 fields: `purchaseState` and `purchaseStateAndroid`. `purchaseState` return 0 while `purchaseStateAndroid ` return 1. Can you explain the difference between 2 field ?

Please open a new thread for a new discussion. Love to see all your kindness tough.
Actually, please check once again since `react-native-iap` should not return `purchaseState` and only `purchaseStateAndroid`.
