### ISSUE TITLE
requestPurchase not working for android products

### ISSUE THREAD

**Issue by patrick-tresp** [dooboolab/react-native-iap#1166]
### Version of react-native-iap
5.0.1

### Version of react-native
0.63.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
When calling `RNIap.requestPurchase(sku, false)` it should open up native purchase options from android to proceed payment process.

### Actual behavior

`await RNIap.requestPurchase(sku, false)` is `undefined` - no native purchase options. No payment process started.

I doublechecked if the sku is valid ( in code and play store )

Fyi: 
Calling `RNIap.requestSubscription(sku)` leads to expected result: native purchase options are shown to proceed payment process. 

### Tested environment (Emulator? Real Device?)

- Real Device connected to Computer
- use downloaded beta-lane apk from play store

**Comment by patrick-tresp** [comment]
after digging more into this issue, i had to find out, that the device ( not the account ) is somehow caching, if i already "own" an item. This leads to the issue that Error is thrown:

`You already own this item`

Did create another product in store and this could be purchased. Not sure how to deal with the cache issue so far, but module's `RNIap.requestPurchase(sku, false)` for Android is working when google play cache has not saved any previous purchases.

**Comment by Caundy** [comment]
Experiencing a similar issue with react-native v0.63.4 and react-native-iap v5.2.3, app ran locally on an android device.

After the initial subscription purchase using the `RNIap.requestSubscription(sku, false)` method (wrapped in `try-catch`), on subsequent purchase attempts the device displays the "You already own this item" error, an error gets thrown (`Error: You already own this item.`) and instead of triggering the `RNIap.purchaseErrorListener` (with `error.code: IAPErrorCode.E_ALREADY_OWNED`) the code proceeds to the aforementioned catch clause.

Restarting the application appears to solve this issue - even though the subscription is still detected as owned and the "You already own this item" error is displayed to the user, an error isn't thrown from the `RNIap.requestSubscription(sku, false)` - instead the `RNIap.purchaseErrorListener` gets triggered with `error.code: IAPErrorCode.E_ALREADY_OWNED`.

Could anyone weigh in on why that could be?

**Comment by 7dp** [comment]
Experience it too, any solution to this?
