### ISSUE TITLE
Issues with first time purchase and getPurchaseHistory

### ISSUE THREAD

**Issue by jortegano** [dooboolab/react-native-iap#1192]
### Version of react-native-iap
5.1.1
### Version of react-native
0.61.5
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Using a sandbox account, after user signs In, if the user request a purchase, the user is prompted only once for purchase.

`RNIap.getPurchaseHistory()` returns `consumable` purchases
### Actual behavior
After user signs In(to get purchase history using `RNIap.getPurchaseHistory()`), in the first purchase, user is prompted twice for purchase.

First time nothing happens after user authtenticates (no events on `purchaseUpdatedListener` nor on `purchaseErrorListener`) but the payment overlay pops out again and the second time everything works as expected.

In next purchase attempts everything works as expected.

Also `RNIap.getPurchaseHistory()` is only returning `non-consumable` purchases.
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
I was able to replicate the issue using the example source code by doing 2 modifications:

- Use `RNIap.getPurchaseHistory()` in `getAvailablePurchases` method
- Use a `non-consumable` product

Steps:

- Sign out of any sandbox account
- Open the app
- Try to get available purchases (you should get prompted to sign in)
- Request a purchase

**Comment by lasryaric** [comment]
Same issue here, do you know if it happens only with sandbox accounts or in production too?

We are hitting that bug in Sandbox, we have yet to go in production.

**Comment by iaphub** [comment]
This is unfortunately an issue related with StoreKit, I don't think there is anything we can do on react-native-iap.
I haven't seen this issue in production (yet).
Also I do not recommend using `getPurchaseHistory` to validate a user purchase, it is normal consumables are not returned because they are not restorable (https://developer.apple.com/documentation/storekit/skpaymentqueue/1506123-restorecompletedtransactions).
Validating your purchases on the server side in the way to go and if you're looking for the easiest solution it's [here](https://github.com/iaphub/react-native-iaphub) 🙂
