### ISSUE TITLE
getProducts() localizedPrice shows price based on language, not country

### ISSUE THREAD

**Issue by karlludwigweise** [dooboolab/react-native-iap#1193]
### Version of react-native-iap

5.1.2

### Version of react-native

0.63.3

### Platforms you faced the error (IOS or Android or both?)

iOS 14 (not using Android)

### Expected behavior

When calling `getProducts()` I expect to get a `localizedPrice` for each `Product`, that matches the AppStoreConnect Country preferences.

### Actual behavior

I am always getting a Dollar Price, but should get a euro price.

### Tested environment (Emulator? Real Device?)

* Real Apple Device as local `Release` build and
* Real Apple Device in Testflight

### Steps to reproduce the behavior

Calling `getProducts();`

**Comment by cardiohelge** [comment]
Any news on this? Currently experiencing the same thing. (What's your solution?)

**Comment by karlludwigweise** [comment]
Yes. It's fixed in v5.1.3 (tested in Germany)

**Comment by cardiohelge** [comment]
Well I tested on v5.1.3 and v5.2.0. Both return the localizedPrize as USD. 
I have german localization provided for the subscribtion and group (plus prices...). Additionally, the phones language and region is german. Testing on real device.
Got some hints?

**Comment by karlludwigweise** [comment]
Did you run `pod install`?
I also have tested on
* a real device
* with Germany as region
* and German als Language
* in Release mode

Not sure, if this matters, but maybe the App Store Account is more relevant than the device settings.

**Comment by cardiohelge** [comment]
So I have the solution now: 

The problem was, what the comment describes here: [https://stackoverflow.com/a/64381619](https://stackoverflow.com/a/64381619)

As this is my first time testing the iap, I was never requesting the subscription but searching for the "localizedPrice" bug.
Therefore the testflight did not know my location or whatever. Now after requesting the subscription and logging in with the apple id, it shows prices in EUR.
