### ISSUE TITLE
Getting the old transaction receipt when subscribe in iOS

### ISSUE THREAD

**Issue by leelasahuinnodeed** [dooboolab/react-native-iap#1301]
### Expected behavior 
It should return the current subscribed receipt. 

### Actual behavior
When subscribe in iOS. all the steps is working correctly. But when purchase listener getting called, it returns the old receipt. When server is validating the receipt then it is getting expired token issue.

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by j-cheung** [comment]
Hi! not sure if it was the same problem.

We encountered an issue where when verifying, we were actually checking the **first,** receipt instead of the **latest**, hence the subscription is 'expired'. 

To fix this, when we verify the receipt on our server, we check the **latest** receipt (first receipt in latest_receipt_info array of the reciept object)

**Comment by leelasahuinnodeed** [comment]
We are actually using the latest_receipt_info array. Some times its get subscribed with last subscribed product.
for example:

I subscribed product 1 -> get expired token
then I subscribed product 2 -> product 1 subscribed.
but this is also not happen every time

**Comment by leelasahuinnodeed** [comment]
The iOS subscription was working earlier before a month in the same build
