### ISSUE TITLE
Pending Transactions after Successfull Payment

### ISSUE THREAD

**Issue by olgunkaya** [dooboolab/react-native-iap#1304]
### Version of react-native-iap
"react-native-iap": "^6.0.2",

### Version of react-native
"react-native": "0.63.3",

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Following a successfull purchase and calling finishTransaction should complete a transaction. 

### Actual behavior
Once we call getPendingPurchasesIOS() app still shows the previously finished transaction in the response. 

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

I think we are missing a fundamental part or our backend missing something. But not sure how to check or test this behavior ?

**Comment by Zovube** [comment]
Same issue.

Looks like `finishTransaction` / `finishTransactionIOS` does not finish transaction - for me `purchaseUpdatedListener` keeps receiving purchases processed with `finishTransaction` / `finishTransactionIOS`. These purchases also appear in `getPendingPurchasesIOS` and `getAvailablePurchases` (which should not be the case, because I tested with consumables).

**Comment by ApargMobile** [comment]
I have the same problem.

**Comment by Zovube** [comment]
@ApargMobile @olgunkaya Is this issue still reproducible for you? Seem to self fix for me 🤔

**Comment by aidan2129** [comment]
Same issue here works perfect on android but on ios i have now ended up with 100+ old purchases triggering the purchase listener on app launch. I added logging in RNIapIos.m to log the SKPaymentTransactionState and they all had the status "purchased" so no idea why they are still calling purchase update listener.

**Comment by olgunkaya** [comment]
I need to check with the team but seems like @aidan2129 still facing. Means we are possibly facing too :)

**Comment by Zovube** [comment]
Yep, self fix is really strange. I have not debugged native part, but If the transactions are actually finished and the only problem is triggering purchase update listener/getting outdated available purchases then this can be fixed by tracking the fact of delivering purchased items to the user in your own database and ignoring already processed receipts. Though probably that's an obvious step, we missed it and plan to add in our project to prevent regression of this issue. In case transactions are not actually finished, this can help to at least keep business logic correct, although, if not acknowledged, purchases will be refunded after some time (have not tested it, but docs say so).

**Comment by olgunkaya** [comment]
Well If call finish transaction and there is no error response back then I would assume this already handled on either iap provider side or the react-native-iap side. I also thought of keeping the track of purhcases on my own DB but isn't it share responsibility of a single action to two different applications. In case of an issue what will be our guy to talk to or check ? :)

**Comment by aidan2129** [comment]
@olgunkaya  Yeah i was under the same assumption seeing the finishTransaction method being called nativley in xcode for every transaction yet i relaunch the app and they are triggered again, it is so frustrating.

**Comment by Zovube** [comment]
Sure, that's not how it should work, finished transactions should not be triggered again and ideally we should not filter transaction based on data from our DB. But as an additional safe check I thinks it's worth adding and in general it's helpful to have as much information as possible available on your side, without relying on 3-rd party tools (especially in such sensitive area as in-app purchases).

**Comment by Tanuja0049** [comment]
Hi, We are getting similar issue on IOS. We are using finishTransaction to complete the transaction, but it seems that purchaseUpdatedListener still sending out these completed transactions. This is causing duplicate transaction at our application side.

**Comment by hardmaster92** [comment]
I have the same issue as well

**Comment by andresesfm** [comment]
Can somebody please confirm this is happening on 8.x.x? If so, can somebody please provide a way to reproduce using IapExaple?

I have found the following as something that is expected from the native SDK: https://stackoverflow.com/a/3633571/570612
If it still happens on 8.x.x and the above doesn't fix. We'll reopen. Thank you

Note: I'm not trying to minimize the issue. I see there are multiple posts about it in various forms and I'm trying to make sense of it but with no help and it being reported on such an old version of the library is close to impossible. Thank you for understanding
