### ISSUE TITLE
undefined is not an object (evaluating 'RNIapModule.prepare')

### ISSUE THREAD

**Issue by vishalgadhiya91** [dooboolab/react-native-iap#161]
### Version of react-native-iap
1.0.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Working
### Actual behavior
undefined is not an object (evaluating 'RNIapModule.prepare')
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

My Project is configured with expo

Steps
npm install — save react-native-iap
react-native link react-native-iap

### Already Tryout
- Detach expo(exp detach) and link (react-native link react-native-iap) but not work
- UN Link and re link (react-native-iap) but its give same error

Whats problem here ???

**Comment by dooboolab** [comment]
@vishalgadhiya91 Could you try to open up the android studio and do `clean` and `rebuild`? That may happen because our module is not linked to your project properly.

**Comment by dooboolab** [comment]
@vishalgadhiya91 Still having problem? Please try linking other libraries too because you might have trouble in linking and not our module. Try something like [react-native-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) which is simple easy one. Detached expo app should do this with np.
