### ISSUE TITLE
android promo code option does not appear, ios offer code cannot be redeemed

### ISSUE THREAD

**Issue by lincdh** [dooboolab/react-native-iap#1875]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

on iOS I have created an offer code for the expected subscription and use the Offer Code URL with the correct CODE to redeem it.

I also try with `presentCodeRedemptionSheetIOS()` but it always return a modal with cannot redeem code, try another code.

on Android I have created an promo code for the expected subscription. And expecting when checkout modal popups there will be promo code option but no.

**Expected Behavior**

ios: should redeem code successfully and return a success modal

android: should show promo code option at checkout modal

**Screenshots**

![Screen Shot 2022-08-18 at 15 21 39](https://user-images.githubusercontent.com/21136244/185347075-9132633b-272e-4950-a524-c96562499a11.png)
![Screen Shot 2022-08-18 at 15 23 09](https://user-images.githubusercontent.com/21136244/185347204-4a13a012-d46d-4c75-9060-658d49663143.png)
![Screen Shot 2022-08-18 at 15 51 49](https://user-images.githubusercontent.com/21136244/185353627-36a18830-9be4-43fe-9384-de2b3d067b72.png)
![Screen Shot 2022-08-18 at 15 24 19](https://user-images.githubusercontent.com/21136244/185347596-091abc4e-5185-4e42-b6a7-861a2b13ccf2.png)

**Environment:**

- react-native-iap: 9.0.3
- react-native: 0.64.2
- Platforms (iOS, Android, emulator, simulator, device): real devices

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by andresesfm** [comment]
Hello @lincdh, can you please point me to the native documentation or an example of what it should look like?

**Comment by andresesfm** [comment]
For Android it should be in the payment options as per: https://developer.android.com/static/images/google/play/billing/promo-payment-methods.png

**Comment by lincdh** [comment]
@andresesfm Here it is inn test mode.
![Screen Shot 2022-08-20 at 01 25 45](https://user-images.githubusercontent.com/21136244/185683712-651939a5-7d6e-4a9f-9a28-47357498c368.png)

**Comment by andresesfm** [comment]
Yeah, I think that's the expected behavior for a test purchase

**Comment by PoCk3T** [comment]
@andresesfm how come is "this" (not showing a redeem option" with react-native-iap library) the expected behavior? For Android at least, the Google doc. clearly shows the "Redeem code" option should be there even for testing: https://developer.android.com/google/play/billing/test#promo

<img width="839" alt="Screenshot 2024-01-11 at 9 04 58 PM" src="https://github.com/dooboolab-community/react-native-iap/assets/685775/636ff6f0-3149-4d5c-8211-0318ae0e9a5a">

**Comment by SufianBabri** [comment]
@Forsaken-sl for Android I am using a custom approach as Android doesn't seem to have an out-of-the-box solution to offer discounts. The flow is like this:
1. create separate offers (percentage or absolute discounts) inside a subscription plan
2. the API on our server validates the coupon code entered and returns the combination of subscription plan, base plan id and offer id
3. When the user applies a coupon code, they are actually buying a plan with discount

For iOS, Apple seems to have a solution but so far I haven't yet tested it because it works on live only. I have shared my findings and a way to test it in the discussion. Please check [this post](https://github.com/dooboolab-community/react-native-iap/discussions/2697#discussioncomment-8916982).
