### ISSUE TITLE
Error: An unknown error occured - RNIap.requestPurchase()

### ISSUE THREAD

**Issue by Mansiwebiots** [dooboolab/react-native-iap#1890]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

Hello

I'm facing an issue while implementing IAP with ios, in the sandbox the payment is working properly but in production, I'm getting this error after I add my apple id and password.

![2022-8-25 12 47 1 192](https://user-images.githubusercontent.com/53261194/186610118-8977e55b-9234-41ae-9aa5-290074a79858.jpeg)

**Environment:**

- react-native-iap: 8.6.7
- react-native:0.63.3
- Platforms : IOS

**Comment by andresesfm** [comment]
@Mansiwebiots can you please post some logs so we can take a look?

**Comment by Mansiwebiots** [comment]
@andresesfm I'm only getting An unknown error occurred as an issue but I won't be able to show you because the issue is in production so I'm not getting any logs.

**Comment by hkeithk** [comment]
Seeing something similar on our end here as well. will try to provide some logs here shortly

**Comment by hkeithk** [comment]
This is when I am trying to call requestPurchase on an android device. Not sure if this is very helpful but these are the logs i pulled out of sentry:

`java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
    at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:92)
    at com.facebook.react.bridge.JavaMethodWrapper$2.extractArgument(JavaMethodWrapper.java:46)
    at com.facebook.react.bridge.JavaMethodWrapper$2.extractArgument(JavaMethodWrapper.java:42)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:356)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
    at java.lang.Thread.run(Thread.java:920)`
    

=========================== by in app grouping =====================
in-app (exception of system takes precedence)
exception (ignored because this variant does not have a contributing stacktrace, but the system variant does)
stack-trace
frame (non app frame)
modulejava.lang.Thread
filename (module takes precedence)thread.java
functionrun
frame (non app frame)
modulecom.facebook.react.bridge.queue.MessageQueueThreadImpl$4
filename (module takes precedence)messagequeuethreadimpl.java
functionrun
frame (non app frame)
moduleandroid.os.Looper
filename (module takes precedence)looper.java
functionloop
frame (non app frame)
moduleandroid.os.Looper
filename (module takes precedence)looper.java
functionloopOnce
frame (non app frame)
modulecom.facebook.react.bridge.queue.MessageQueueThreadHandler
filename (module takes precedence)messagequeuethreadhandler.java
functiondispatchMessage
frame (non app frame)
moduleandroid.os.Handler
filename (module takes precedence)handler.java
functiondispatchMessage
frame (non app frame)
moduleandroid.os.Handler
filename (module takes precedence)handler.java
functionhandleCallback
frame (non app frame)
modulecom.facebook.react.bridge.queue.NativeRunnable
filename (module takes precedence)nativerunnable.java
functionrun
frame (non app frame)
modulecom.facebook.react.bridge.JavaModuleWrapper
filename (module takes precedence)javamodulewrapper.java
functioninvoke
frame (non app frame)
modulecom.facebook.react.bridge.JavaMethodWrapper
filename (module takes precedence)javamethodwrapper.java
functioninvoke
frame (non app frame)
modulecom.facebook.react.bridge.JavaMethodWrapper$2
filename (module takes precedence)javamethodwrapper.java
functionextractArgument
frame (non app frame)
modulecom.facebook.react.bridge.JavaMethodWrapper$2
filename (module takes precedence)javamethodwrapper.java
functionextractArgument
frame (non app frame)
modulecom.facebook.react.bridge.ReadableNativeArray
filename (module takes precedence)readablenativearray.java
functiongetDouble

collapse 11 similar
typeNullPointerException
valueAttempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

**Comment by andresesfm** [comment]
@hkeithk What you are reporting is for Android, the original ticket is for iOS Please create an issue using the template

**Comment by andresesfm** [comment]
Could be fixed on the latest release if the error was really an interruption to sign new terms and conditions
