### ISSUE TITLE
Play Store error: DF-DFERH-01

### ISSUE THREAD

**Issue by colaquecez** [dooboolab/react-native-iap#2106]
Version of react-native-iap
12.4.2

Version of react-native
0.64.4

Platforms you faced the error (IOS or Android or both?)
Android

Expected behavior
Buy subscription

Actual behavior
Play Store error: DF-DFERH-01

Tested environment (Emulator? Real Device?)

Pixel_3a_API_33_arm64-v8a (emulator)
Galaxy A32

<div>
<img src="https://user-images.githubusercontent.com/38195454/200726485-d5223988-e3cd-4cae-9a92-79044b25edc9.png" alt="print-mobile" width="200"/>

<img src="https://user-images.githubusercontent.com/38195454/200727073-252858a6-aec9-4036-918b-6bc49cd80c46.png" alt="print-mobile" width="200"/>
<div/>

Steps to reproduce the behavior
I've updated the old version **8.5.0** to the new one **12.4.2** then I've been trying to test it on test internal

That function is working fine when I try to get the subscriptions 

```js
getSubscriptions({skus: productIds});`
```

But when I try to do a subscription using that code:

```js
requestSubscription({
      sku: sku,
      subscriptionOffers: [{sku: sku, offerToken: sku}],
      andDangerouslyFinishTransactionAutomaticallyIOS: false,
    }),
```

I'm getting the error `DF-DFERH-01`, maybe the `offerToken` is wrong, but I don't know if it would cause that error, if so, how can I get that token?

**Comment by andresesfm** [comment]
You can find requestToken as part of the response of getSubscriptions

**Comment by normenster** [comment]
@andresesfm for me it was a wrong call to requestSubscription. We have Subs with 7 days trial and the subscription.
if (Platform.OS === 'android') { subscription.subscriptionOfferDetails.map((sub) => { offers.push({ sku: subscription.productId, offerToken: sub.offerToken, }); }); }

i thought i have to send all offers:

const subme = await requestSubscription({ sku: subscription.productId, subscriptionOffers: offers });

but that creates the error for some users ( i don`t know why it worked with my account).
Only the "real" sub needs to be sent - this worked then:

const subme = await requestSubscription({ sku: subscription.productId, subscriptionOffers: [offers[0]], });

**Comment by bitfabrikken** [comment]
For posterity + people who have searched this error and come here..

@normenster clued me into this and caused me to actually look at the data in product.subscriptionOfferDetails.

I was receiving the same error for an app in production: DF-DFERH-01

It turned out that the product.subscriptionOfferDetails array contained an entry without an offerId, and when that was sent along via requestSubscription, the error occured.

So a possible solution is to only send offers via requestSubscription which have an offerId.

product.subscriptionOfferDetails:
![image](https://user-images.githubusercontent.com/2039652/233352832-8078b33d-1ba2-46bf-a0e1-1caa02eb24a1.png)
