### ISSUE TITLE
getSubscriptions

### ISSUE THREAD

**Issue by anishamalde** [dooboolab/react-native-iap#2140]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

When trying integrate with the Amazon IAP, connected is true but subscriptions returns an empty array.

**Expected Behavior**
Subscriptions should match the SDK Tester JSON
[ 'com.amazon.sample.iap.subscription.mymagazine.month',
 'com.amazon.sample.iap.subscription.mymagazine.quarter']

**Environment:**
- react-native-iap: 12.4.4
- react-native: 0.68.2
- Platforms (iOS, Android, emulator, simulator, device): Amazon Fire Tablet with IAP App tester

**To Reproduce**
Steps to reproduce the behaviour:

```
const {connected, subscriptions, getSubscriptions} = useIAP();

const fetchProducts = useCallback(async (): Promise<void> => {
    getSubscriptions({skus: [
      'com.amazon.sample.iap.subscription.mymagazine.month',
      'com.amazon.sample.iap.subscription.mymagazine.quarter',
    ]});
  }, [ getSubscriptions]);

  useEffect(() => {
    if (connected) {
      fetchProducts();
    }
  }, [fetchProducts, connected]);

```

`export default withIAPContext(App);`

**Comment by andresesfm** [comment]
Have you tried using the IapExample app?

**Comment by andresesfm** [comment]
Can you share your solution @anishamalde?

**Comment by anishamalde** [comment]
Hey Andres, yes, I am trying to use the hooks as above with an Expo app. I know the solution won't work the Expo go but even when i compile the app and try and run it on my Amazon device it doesn't fetch the subscriptions.
https://github.com/anishamalde/RNTVDemo/tree/iap

**Comment by Arthur092** [comment]
Hi @anishamalde  !

Writing you because I just had a similar issue with the Example App:
I followed your article:
https://dev.to/amazonappdev/react-native-iap-one-package-to-rule-them-all-4f0n

And also I am running the app with `adb shell setprop debug.amazon.sandboxmode debug`
on my amazon fire tablet

But when calling getSubscription nothing happens (never pass the await getSubscriptions({skus: constants.subscriptionSkus}))

Do you have an idea what might be happening?

**Comment by vasihc** [comment]
Hi @anishamalde @Arthur092! 
Did you solve this issue?
