### ISSUE TITLE
Document is not correct anymore?

### ISSUE THREAD

**Issue by Norcy** [dooboolab/react-native-iap#2164]
> Please use the [Discussion board](https://github.com/dooboolab/react-native-iap/discussions) if you want to get some help. Please use issues to report bugs.

**Description**

When config iOS environment by the [document](https://react-native-iap.dooboolab.com/docs/guides/purchases)，I found that many methods are not corresponding to the code

For example，following codes which are copied from [document](https://react-native-iap.dooboolab.com/docs/guides/purchases) are not compiled successfully, the function call itself forever?

```js
requestSubscription = async (sku: string, offerToken: string?) => {
    try {
      await requestSubscription(
        {sku},
        ...(offerToken && {subscriptionOffers: [{sku, offerToken}]}),
      );
    } catch (err) {
      console.warn(err.code, err.message);
    }
  };
```

**Expected Behavior**

**Screenshots**

**Environment:**

- react-native-iap:12.4.9
- react-native:0.62.2
- Platforms (iOS, Android, emulator, simulator, device):iOS

**To Reproduce**

2. Press '...'
3. Error '...' is shown

---

[Optional] **Additional Context**

**Comment by UFFETKK** [comment]
try this
`const requestSubscriptionPurchase = async (offerToken, sku) => {
    const subscriptionRequest = {
      subscriptionOffers: [
        {
          sku,
          offerToken,
        },
      ],
    };
    try {
      if (Platform.OS == "android") {
        await RNIap.requestSubscription(subscriptionRequest);
      } else {
        RNIap.requestSubscription(product?.productId, null);
      }
    } catch (error) {
      console.log(error);
    }
  };`

**Comment by andresesfm** [comment]
@Norcy, that code is correct and it would not call itself recursively. the method names are overloading the ones coming from the library. You can see them working in the Example app. Having said that I see how it can be confusing. I have updated the names and explicitly added the imports to avoid confusion: https://github.com/dooboolab/react-native-iap/pull/2182 

@UFFETKK that would not work as for iOS you also need the subscriptionRequest object instead of individual parameters.
