### ISSUE TITLE
subscriptionOffers are required for Google Play Subscriptions : android

### ISSUE THREAD

**Issue by chiragmakwana000** [dooboolab/react-native-iap#2194]
Calling RNIap.requestSubscription(sku)
results in an error being thrown: "subscriptionOffers are required for Google Play Subscriptions"

**Environment**
react-native-iap : '^12.4.12'
react-native:'0.67.4'

Working fine on ios but not working on android.

**Comment by chiragmakwana000** [comment]
[This is has been closed](https://github.com/dooboolab/react-native-iap/issues/2155)

**Comment by chiragmakwana000** [comment]
https://github.com/dooboolab/react-native-iap/issues/2155
This issue has been added previously but resolved yet.
Please don't tag this as duplicate.
[Android: purchase Subscription error: "subscriptionOffers are required for Google Play Subscriptions"](https://github.com/dooboolab/react-native-iap/issues/2155)

**Comment by andresesfm** [comment]
@chiragmakwana000 this is not an issue, that field is needed by the native SDK. It is not artificially added by this library. It works as expected. See the Example app for how to use it. Note that this is not a duplicate because #2155 is passing the expected object where as yours is passing a single string wich would not work on iOS either

**Comment by chiragmakwana000** [comment]
@andresesfm 

Can you please able to share a working example of this  ? 
 **RNIap.requestSubscription(sku)**

**Comment by andresesfm** [comment]
Look in the repo IapExample

**Comment by gtebbutt** [comment]
@andresesfm  If I'm understanding correctly this looks like a documentation question rather than a functionality problem? Right now `requestSubscription` and `requestPurchase` say that they take `{sku: productID}`, but from the code it looks like that should be updated to `{subscriptionOffers: []}` and `{skus: []}` respectively on Android. 

It's also a little tricky to find a lot of the main function documentation right now (`getProducts`, `requestPurchase`, etc.) since it's not listed under `API Reference -> Methods >` or `api -> modules >`, only in the long export list under the second `api -> modules` heading which is quite easy to miss.

**Comment by serkansentilay** [comment]
any solving?

**Comment by shivanitp** [comment]
may it's work 

const subscriptionOffers = [{sku,offerToken,}]
var purchase = await RNIap.requestSubscription({ subscriptionOffers });

**Comment by chiragmakwana000** [comment]
Solved from [example](https://github.com/dooboolab/react-native-iap/blob/main/IapExample/src/screens/Subscriptions.tsx)

**Comment by andresesfm** [comment]
Making docs less confusing: https://github.com/dooboolab/react-native-iap/pull/2202 let me know if any questions
