### ISSUE TITLE
requestPurchase return E_UKNOWN and error code: 6

### ISSUE THREAD

**Issue by wailin0** [dooboolab/react-native-iap#2233]
Can anyone help me why it's happening. 
 I got the same unexpected error for both in app purchase and subscription.

![Screenshot_2023-02-03-13-39-57-273_com android vending](https://user-images.githubusercontent.com/61951765/216535612-53f443eb-6d27-4d53-8127-854262cf55fb.jpg)
![Screenshot_2023-02-03-13-40-04-489_com android vending](https://user-images.githubusercontent.com/61951765/216535626-dbf9a08d-fa07-421e-ba6a-74334e34f2dc.jpg)

**Comment by Haider-Ali-7** [comment]
Hi @wailin0, I'm having the same issue. I've been trying to debug it for three days. Were you able to resolve this?

**Comment by wailin0** [comment]
> Hi @wailin0, I'm having the same issue. I've been trying to debug it for three days. Were you able to resolve this?

yes. for my case, the issue was solved when i used vpn for testing purchase api

**Comment by Haider-Ali-7** [comment]
It is kind of strange. Because when I was testing, I requested too many purchases and subscriptions. I was using finishTransaction as well. But after waiting for a week, it starts working again which gives me impression that iap sdk needs time to clear its cache. Because if i do it manually or delete the app, it doesn't work. Good to know your solution.
