### ISSUE TITLE
[question] Whats the point on restoring purchases? 

### ISSUE THREAD

**Issue by nriccar** [dooboolab/react-native-iap#2403]
Hello to all!

First of all, thanks for reading.

I have this doubt, it could seem naive from my part but I don't really get the point.
If a user subscribes to a auto-renewal subscription, it will get access to X part on my app. We save that information in our DB.

If the same user wants to access that subscription from another device, our app would ask for login, and after it, that subscription would be accessible.

What does it do the restore purchase action itself?

**Comment by hszouszcz** [comment]
Actually it's great question and I would like to hear some thoughts about this too. When such situation can take place if you store subscription data on BE?

**Comment by goguda** [comment]
> 

I remember back in the day, especially on iOS, a lot of apps would lose purchases if you deleted the app from your device since everything was stored locally. If you reinstalled, you could "restore purchases" which would essentially tell the app you've already paid for certain IAPs so it could store that info locally and grant access to the paid feature(s) again.

With modern server-side storage, there seems to be less of a need for this, but I suppose they've left the functionality there for people that still want to store everything locally on the user's device.

If you're storing the data server-side, you probably don't need to use the restore purchases function.

**Comment by goguda** [comment]
> Hello to all!
> 
> First of all, thanks for reading.
> 
> I have this doubt, it could seem naive from my part but I don't really get the point. If a user subscribes to a auto-renewal subscription, it will get access to X part on my app. We save that information in our DB.
> 
> If the same user wants to access that subscription from another device, our app would ask for login, and after it, that subscription would be accessible.
> 
> What does it do the restore purchase action itself?

I remember back in the day, especially on iOS, a lot of apps would lose purchases if you deleted the app from your device since everything was stored locally. If you reinstalled, you could "restore purchases" which would essentially tell the app you've already paid for certain IAPs so it could store that info locally and grant access to the paid feature(s) again.

With modern server-side storage, there seems to be less of a need for this, but I suppose they've left the functionality there for people that still want to store everything locally on the user's device.

If you're storing the data server-side, you probably don't need to use the restore purchases function.
