### ISSUE TITLE
Provide access to SKReceiptRefreshRequest on iOS

### ISSUE THREAD

**Issue by schumannd** [dooboolab/react-native-iap#337]
currently both getAvailablePurchases and getPurchaseHistory call the same method on iOS which uses `restoreCompletedTransactions`.

The problem with this method is [this intermittent issue](https://stackoverflow.com/questions/42312927/apple-in-app-purchase-transaction-id-of-one-purchase-changes-sometimes). As an alternative to circumvent this issue it is suggested to use SKReceiptRefreshRequest to get the latest purchase.

I don't know if there is a similar function on android. But it would be useful to provide access to the API on iOS.

**Comment by JJMoon** [comment]
I think it's cross platform issue and lousy Apple IAP system issue. Anyway, I don't remember why the two methods have same functionality. It's because of the naming convention and differences between iOS and Android. @hyochan and I will discuss about the naming. 
About the intermittent issue about SKReceiptRefreshRequest, and restoring action changing the transaction ID, I suggest you to use receipt itself. Not the ID. I don't know this is possible, but when the App is restoring, the receipts are important, not the ID. There are other useful infos like purchasing dates.

**Comment by Loopiezlol** [comment]
Hey, was wondering what is the status on this? I am interested in helping with the implementation - (in a week + as I have my hands full with my disseration atm).

After launching an IAP subscription to prod, been noticing some weird payloads returned by the ios verification endpoint, where no actual receipts are in the `latest_receipt_info` or `in_app` fields

What made it even weird, `transactionDate` (as sent by the `react-native-iap` on the client ) is `0`.
As many other posts across the web (i.e [this](https://stackoverflow.com/questions/36010595/itunes-reciept-validation-in-app-empty)) mentioned this might be circumvented by this method.
