### ISSUE TITLE
E_UNKNOWN, Cannot connect to iTunes Store.(IPv6)

### ISSUE THREAD

**Issue by ravishankar3961** [dooboolab/react-native-iap#357]
### Version of react-native-iap
    react-native-iap : 2.3.26
### Version of expokit
 expokit : 31.0.2
 expo : 31.0.2
### Version of react-native
 react-native : 0.57.1
### Network Type
IPv6
Testing App on the real device on IPv6,
### Platforms you faced the error (IOS or Android or both?)
Both
### Expected behavior
Purchase the Non-Consumable product successfully
### Actual behavior
E_UNKNOWN, Cannot connect to iTunes Store
### Tested environment (Emulator? Real Device?)
Device
### Steps to reproduce the behavior
Every time I call the following methods, it shows "E_UNKNOWN, Cannot connect to iTunes Store", on the IPv6 network:-
getProducts(),
buyProductWithoutFinishTransaction(),
buyProduct(),
getAvailablePurchases()

I don't know about other methods but getting the above error on the these methods.

**Comment by hyochan** [comment]
Closing this and will follow up this in #174. Expo currently don't support native modules.

**Comment by robertherber** [comment]
I'm suspecting I have a similar issue, although I haven't been able to confirm it. 

There is nothing that suggests this has to do with Expo (expect the coincidence of both me and @ravishankar3961 working with detached Expo apps) - since as far as I know Expo only adds functionality on top of React Native - it doesn't change React Native Core functionality which is what this library depends on.

Could we open this again @hyochan? We should keep this separate from the issue of integrating with (unejected) Expo apps.
