### ISSUE TITLE
Sending iap-purchase-event with no listeners registered

### ISSUE THREAD

**Issue by d7laungani** [dooboolab/react-native-iap#369]
### Version of react-native-iap
2.4.0-beta6
### Version of react-native
https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz
### Platforms you faced the error (IOS or Android or both?)
ONLY IOS
### Expected behavior
.then is hit after    const purchase = await RNIap.buySubscription(sku).then(purchase => {
### Actual behavior
After a successful subscription and I get the message that the purchase is complete this pops up on the iphone ('Sending iap-purchase-event with no listeners registered')
Error in try catch is not hit either
### Tested environment (Emulator? Real Device?)
Real Device - Iphone 6s
### Steps to reproduce the behavior
```
  const purchase = await RNIap.buySubscription(sku).then(purchase => {
               
      RNIap.finishTransaction();
              
      console.log('purchase complete')
     return purchase
  }).catch(err => {
    // resetting UI
    //console.log('after itunes cancel or error', err.msg)
  })
```

**Comment by hyochan** [comment]
You are receiving this because of the recent feature we've implemented. See [this](https://github.com/dooboolab/react-native-iap#purchase-example-3-advanced). I think you can ignore the error message and hopefully I think that doesn't affect your current code. 

In addition to that, I can see easily that your code is wrong because you are using `await` and `then` at the same time. Please use one of them.

Please come back when you think this should be reopened.
