### ISSUE TITLE
Check if user is signed into iTunes Store

### ISSUE THREAD

**Issue by augustbjornberg** [dooboolab/react-native-iap#371]
Question/Feature request:

If a user is reinstalling the app, and on a previous install made non-consumable in app purchases, i would like to attempt to restore the functionality that the user has previously paid for.

I'm currently able to query if the user has previously purchased any extra content. However, if the user is not logged into the iTunes store, they will be greeted with an iTunes login. Although very few users wont be logged in, i really wouldn't want that to happen – my app asking the user to log into the iTunes Store immediately on the first launch would look really fishy.

Ideally i would only attempt to check the previous purchases if the user is already logged into iTunes, and i'm able to check the previous purchases silently.

Is this possible to do using react-native-iap?

[Link to question on Stack Overflow](https://stackoverflow.com/questions/54281712/ios-check-if-user-is-signed-into-itunes-store)

### Version of react-native-iap
2.4.0-beta6

### Version of react-native
0.56.0

### Platforms you faced the error (IOS or Android or both?)
iOS

**Comment by marf** [comment]
Same problem here

**Comment by kevinEsherick** [comment]
@augustbjornberg how are you able to query their purchases without prompting them to login? getPurchaseHistory prompts iTunes login even if they're signed in. Is there another method?

And, not that this is a fix, but if they just downloaded your app it will be exceedingly rare that they won't be signed in because they would have to be signed in to download it. Such a rare edge case as to possibly not be worth your time, though I understand where you're coming from. But from what I can see there is no method to check this. Would be interested to hear if you find otherwise.

**Comment by 13ArturBruno** [comment]
My case I am not logged in to the device, and in the application I am logged in to an account and I can not loggout

**Comment by hyochan** [comment]
I think this couldn't be fixed since `apple` doesn't have the solution. [See link](https://stackoverflow.com/questions/29978794/detect-if-user-is-signed-in-in-the-itunes-store).
