### ISSUE TITLE
[IOS] Can't recognize the purchase after Registering a card because of non-registered card

### ISSUE THREAD

**Issue by yansfil** [dooboolab/react-native-iap#394]
![kakaotalk_photo_2019-02-07-11-34-56](https://user-images.githubusercontent.com/14955500/52387157-6e13d800-2acc-11e9-94f6-a39793f144f9.jpeg)

Our clients who couldn't get coins after purchase increases.
because Clients didn't register card or write wrong informations, IAP let them go to ios-play-store and force to input new card infos. After that, Purchase was successful(money came out) on ios-playstore. And return to our application, it didn't recognize that. As you can see Above the picture, client try again to purchase.. but it can't

```
try {
                const {sendIapReceipt} = this.props
                const purchase = await RNIap.buyProduct(item.iapItemName)
                const receipt = purchase.transactionReceipt
                if (receipt) {
                    sendIapReceipt({receipt}).then(result => {
                        Toast.show('결제가 완료되었습니다.', Toast.SHORT)
                    }).catch(err => {
                        alert('결제 오류가 발생했습니다. 고객센터에 연락해주세요.')
                    })
                }
            } catch (e) {
                Toast.show(e.toString(), Toast.SHORT)
                const subscription = RNIap.addAdditionalSuccessPurchaseListenerIOS(async (purchase) => {
                    const receipt = purchase.transactionReceipt
                    const {sendIapReceipt} = this.props
                    if (receipt) {
                        sendIapReceipt({receipt}).then(result => {
                            Toast.show('결제가 완료되었습니다.', Toast.SHORT)
                        }).catch(err => {
                            alert('결제 오류가 발생했습니다. 고객센터에 연락해주세요.')
                        })
                    }
                    subscription.remove();
                });
            }
```

**Comment by hyochan** [comment]
Yeah, this was one of the critical issues we've faced in #307 and I've supported this in #348. You can go over the [readme](https://github.com/dooboolab/react-native-iap#purchase-example-3-advanced) and see how to add this feature.

Also, I hope your company can participate as a [backers](https://opencollective.com/react-native-iap#backers) of our module because this becomes quite large to be handled by just me. I am spending quite a few times maintaining this but I am still seeing quite many issues not covered yet that needs some dev's participation. I'm planning to participate in `issue hunter` if some backers support this.

P.S. As a billing library update, it is just a burden for me to handle `migration` to cover an issue like #391. Hope there is some help out there to maintain this.

**Comment by hyochan** [comment]
I just looked into this again, and I think you are facing a different problem. Are you really sure that you are not getting the value out of `addAdditionalSuccessPurchaseListenerIOS`? I think you want the customers to actually rebuy the item. Looks like the products should be `consumable` but I think it is currently `non-consumable`.

**Comment by hyochan** [comment]
Closed for inactivity.
