### ISSUE TITLE
How to make iOS UI similar to Android experience?

### ISSUE THREAD

**Issue by zaynv** [dooboolab/react-native-iap#442]
### Version of react-native-iap
Latest

### Version of react-native
Latest

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
I was hoping the UI would look nice like Android. Something like this:

![1](https://user-images.githubusercontent.com/8627403/55237021-91731d80-5207-11e9-8733-844650161f8f.png)

or something like `react-native-payments`:

![2](https://user-images.githubusercontent.com/8627403/55237032-9768fe80-5207-11e9-824a-2efe8fb717a2.png)

### Actual behavior
It currently only shows an Alert when you call the method to buy a product on iOS.

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
Call buyProduct or buySubscription on iOS

Thanks very much for this library.

**Comment by hyochan** [comment]
The popup in `iOS` is system default, so I don't think we can do anything about it.

**Comment by dengue8830** [comment]
in other apps like blinklist there use a cool modal like @zaynv shows. May be it depends on the version of some internal lib you are using

other app:
![IMG_0119](https://user-images.githubusercontent.com/5104213/57492087-dcb42d80-7295-11e9-8417-324fbeec766a.PNG)

my app :'v
![IMG_0115](https://user-images.githubusercontent.com/5104213/57492115-eb024980-7295-11e9-94be-9b4f100e2665.PNG)

its the same phone

**Comment by saadq** [comment]
It seems that it may just be due to the current environment you're in. There was a similar [post on Reddit](https://www.reddit.com/r/reactnative/comments/babgn4/iosreact_native_inapppurchases_specific_popup/ekdw39w/) about this issue, and they mentioned that the plain popup is only during development and that the nice popup comes when you install the app from the App Store. I have not tested it yet though, so can't confirm.
