### ISSUE TITLE
Receipt not getting after successful subscription

### ISSUE THREAD

**Issue by binil1931** [dooboolab/react-native-iap#567]
#3.0.0# Version of react-native-iap

##0.57.8 Version of react-native

### Expected behavior
after subscription get receipt

### Actual behavior
receipt not getting 

### Steps to reproduce the behavior
    _subscribe(){
      RNIap.requestSubscription('sub_1').then(purchase => {
        console.log("inApp Subscription transactionReceipt ",purchase.transactionReceipt);
       }).catch((error) => {
        console.log("inApp Subscription error",error.message);
       })
    }

**Comment by hyochan** [comment]
I hope your issue to be more detailed. Which platform are you facing this and is this a `error` message returned in `catch` statement?

Also please try to use recent version of `3.0.0` which will be `3.1.0` for < 0.59 and `3.2.3` for >= `0.60` for react-native.

**Comment by bgrynblat** [comment]
@hyochan I think I am facing a similar issue on Android only with version 3.0.0. Unfortunately I can't upgrade since I cannot migrate to AndroidX, mandatory since 3.1.0.

When using `RNIap.requestSubscription(pid)`, and after successfully subscribing with Android Play Store, the callback is never called. For instance :

```RNIap.requestSubscription('sub_1').then(purchase => {
    // WE NEVER REACH THIS POINT EVEN AFTER A SUCCESSFUL SUBSCRIPTION
}).catch((error) => {
    console.log("inApp Subscription error",error.message);
})```

Please note this only happens on Android, not on iOS.

Any idea ?

Thanks 🙏

**Comment by hyochan** [comment]
You can still use 3.0.2
