### ISSUE TITLE
Linking issue: 'React/RCTDefines.h' file not found

### ISSUE THREAD

**Issue by iSaadSalman** [dooboolab/react-native-iap#6]
I'm facing this linking issue "'React/RCTDefines.h' file not found"

I using expo version of react native 0.48.4 (21.0.2 expo) & react-native-iap version 0.1.10

Could you help me with this?
Thanks

**Comment by KjellConnelly** [comment]
@iSaadSalman 
Expo doesn't work with react-native-iap unless you detached, nor do repos with native code in them. If you did detach, this is a linking issue that is common with React Native projects. Try a google search to find a solution as you'll find the same problem with other native modules you add and isn't specific to this git repo.

**Comment by iSaadSalman** [comment]
@KjellConnelly I did indeed detached. Just the sdk version of react-native is expo curated.

I have couple of modules like 
@expo/vector-icons
and react-native-fbsdk
which are linked but do not give this issue

--

Regarding the issue, I searched but could not get hold of the correct answer. Also, I'm quite new to this so if you have experienced this issue and found the solution, please point me in the right direction.

**Comment by dooboolab** [comment]
@iSaadSalman 
KjellConnelly is definitely right for this. The vector-icons is not linked to your project it is just inside expo. You are miss understanding about react-native link and expo sdk. Expo sdk imbeds library that should be linked by users but if those libraries are not insdie expo sdk, you need to detach from it. Above two library you mentioned is not needed to detach because it is already in expo. Below screenshot will help you how to link our library to detached expo. Check it out~
-------------------------
![image](https://user-images.githubusercontent.com/27461460/34078267-fe312d22-e359-11e7-9160-e15d86afae36.png)
