### ISSUE TITLE
In what case should i store the receipt ? 

### ISSUE THREAD

**Issue by hikkary** [dooboolab/react-native-iap#655]
Hi,

First of all thank you for this package, I just have a question regarding good practice with in app purchase, I used this package for one of my app and I did not store the receipt, the purchase only remove ads. 

I just use RNIap.getPurchaseHistory() to restore purchase. I wanted to know if it's a good practice or am I doing really bad.

in what case storing receipt is recommended  ?

thank you !

**Comment by hyochan** [comment]
You need to store your `receipt` in production to track the previous purchases (especially for your ios consumable products since this isn't stored anywhere in `ios` side). It also prevents fake purchases by validating it.

**Comment by hikkary** [comment]
Ok ! Thank you @hyochan ! How Do I differentiate users ? They are no authentification in my app, does the receipt have this info ?

**Comment by jvandenaardweg** [comment]
> How Do I differentiate users ? They are no authentification in my app, does the receipt have this info ?

You don't really need to differentiate, because the purchase history is tight to the user's Apple ID. So it's unique for each user.

You can connect users in your app to purchases by using the `originalTransactionId` per product/subscription. As a user can only have one `originalTransactionId` per product/subscription.
