### ISSUE TITLE
No any response after changing the subscription plans (Android only)

### ISSUE THREAD

**Issue by AsbarAli** [dooboolab/react-native-iap#707]
### Version of react-native-iap
3.3.9

### Version of react-native
0.59

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Should return any response (Better if receive a receipt)

### Actual behavior
Doesn't return any response

### Tested environment (Emulator? Real Device?)
Real Device - sandbox

### Steps to reproduce the behavior
1. Subscribe to a yearly subscription plan
2. Then change the yearly subscription plan to monthly subscription plan

### Description

1. requestSubscription('yearly')
2. Success
3. Current subscription is active
4. requestSubscription('monthly', 'yearly', 'mode')

Doesn't receive any response to purchaseErrorListener or purchaseUpdateListener

**Comment by AsbarAli** [comment]
We dug into the android native code in Iap module and after changing the subscription plan only _onPurchaseUpdated_ method is triggered in RNIapModule.java file.

only _onPurchaseUpdated_ method is triggered with a null value for purchases argument and _startListening_ method is not invoked.

**Comment by howg0924** [comment]
@AsbarAli We also encountered this problem. Did you find the solution in the end?

We tried RNIap 4.3.0 & 4.3.3, the issue is basically the same. The only difference is the registered purchase error listener will be called with the following error due to [this change](https://github.com/dooboolab/react-native-iap/commit/91c7a31e2b333b962557ea12750718721ca36299) on 3.4.12:

{ message: 'purchases are null.',
  code: 'OK',
  debugMessage: '',
  responseCode: 0 }

@hyochan May you give us some hint on this issue? Thank you so much~.
