### ISSUE TITLE
Displays login dialog each time application is started

### ISSUE THREAD

**Issue by jirgl** [dooboolab/react-native-iap#73]
I just fetched `getProducts`, bought products `buyProduct` and everything was successful. Since first purchase each time I launch application I see login dialog to my account (iOS platform). I am using `0.3.0-alpha1` but I had this problem earlier at `0.2.*`. What am I doing wrong? Code was inspired by example app.

**Comment by JJMoon** [comment]
I have been experiencing exactly same process. I guess it's the iTunes Connect bug.
In order to test IAP in iPhone, you need to logout your account, and login to sandbox tester.
During testing IAP process, you implicitly login with that sandbox account.
But, in this process, you can see some side effects which looks like bugs.
If you use Apple Music service (like me), you lost downloaded songs, and will have problem in logging in afterwards.
If you succeeded purchasing and received receipt, it's OK.

**Comment by jirgl** [comment]
Yes, it looks like a bug at iTunes Connect side. In case of app from TestFlight and tester's account is everything OK. Thank you for your hint.
