### ISSUE TITLE
GetAvailablePurchase return empty array but GetPurchaseHistory does return results

### ISSUE THREAD

**Issue by Sach-SPF** [dooboolab/react-native-iap#852]
### Version of react-native-iap
4.2.2
### Version of react-native
0.59.9
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
GetAvailablePurchase should return results
### Actual behavior
GetAvailablePurchase returns empty array
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
1. Subscribe to test the purchase.
2. FinishTransaction (Acknowledge the purchase).
3. calling getAvailablePurchase return empty array

**Comment by hyochan** [comment]
Wow, this is new to me either. [queryPurchaseHistoryAsync](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#querypurchasehistoryasync) and [queryPurchases](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.html#querypurchases) are the methods we are using for `getPurchaseHistory` and `getAvailablePurchase`.

I am suspecting this might cause a different result in test mode but I hope you can bring us further investigation since I feel you are the closest to the issue.
