### ISSUE TITLE
purchaseErrorListener product sku

### ISSUE THREAD

**Issue by yanush** [dooboolab/react-native-iap#889]
Is there a way to get the product sku of the failed purchase?
In my app I have a store with 6 products (represented by 6 buttons).
When a user tries to buy a product I'm disabling its button and put loader on the button until I get either success or failure.
The problem is that when I get a failure I can't seem to find a way of knowing the failed package sku
Please advise

**Comment by hyochan** [comment]
Since `onPurchaseUpdated` listener doesn't know which purchases have failed since it is all running asynchronously, it is hard to track if you enabled multiple purchases attempts to the user. Why don't you try to handle this one by one and restrict another payment attempt when it is in progress?

**Comment by yanush** [comment]
Currently I'm using the promise returned from requestPurchase to catch errors.
When requestPurchase fails I can tell in the catch section which productId (sku) was sent.
Can't you just emit the sku (or even the entire purchase) to purchaseErrorListener along with the error? you're doing it in purchaseUpdatedListener so it should be the same, no?

**Comment by hyochan** [comment]
Maybe my other library ([react-native-iap](https://medium.com/dooboolab/react-native-iap-v3-1259e0b0c017)) will help you understand this problem. The promise returned from `requestPurchase` is similar to `purchaseErrorListener`. However, I'd not recommend handling this way because when `requesting`, it does not guarantee which purchases attempt should finish the first hand. Therefore, if you are making many attempts at once and trying to handle correct promise rejection, they are not reliable.
