### ISSUE TITLE
E_USER_CANCELLED error, but payment successful 

### ISSUE THREAD

**Issue by yevhenlv** [dooboolab/react-native-iap#935]
Hi. I have one problem on my app with rn-iap. Unfortunately, I can't reproduce it, only fix consequences.

### Version of react-native-iap
4.3.0

### Version of react-native
0.59.10

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Payment process successful

### Actual behavior
Payment success for me (as developer), but appstore or rn-iap return error E_USER_CANCELLED (can't connect to itunes store). User pay his money (successfully), but don't get subscription because app got error.

### Tested environment (Emulator? Real Device?)
Real Device (Production version)

### Steps to reproduce the behavior
Can't reproduce

**Comment by hyochan** [comment]
We are currently working on an example project called [DoobooIAP](https://github.com/hyochan/DoobooIAP) to deliver full featured `react-native-iap` working example. These kind of non-existing reproducible issues are very hard to resolve. I hope you can contribute to our project either!

**Comment by yevhenlv** [comment]
Hi. I can add some info, hope it'll help.
Error appears after RNIap.finishTransaction(purchase)

code E_UNKNOWN
column 1625
domain SKErrorDomain
userInfo.NSLocalizedDescription Cannot connect to iTunes Store

Payment is successful in store, but we get such error and don't give access for user.

I saw proposals RNIap.addAdditionalSuccessPurchaseListenerIOS in similar situations, but now I can't find this method in your docs.

**Comment by hyochan** [comment]
`addAditionalSuccessPurchasListenerIOS` is removed and should not be used. You can see my [medium blog](https://medium.com/dooboolab/react-native-iap-v3-1259e0b0c017).

Refer to [ios forum](https://forums.developer.apple.com/thread/91828), I found may trouble syncing purchases with testflight user for production.

**Comment by yevhenlv** [comment]
Hi. Yes, we don't use this method, but still get problems with payments on ios. Our current version of rn-iap 4.4.3

**Comment by hyochan** [comment]
Looks like this relies on `Apple` and not our module so please check your config first. Going over whole steps again sometimes fixes.
Without any more investigation, I can't move this forward.

**Comment by cumom** [comment]
I think you will get an E_USER_CANCELLED error even though the purchase was successful if you don't wait for RNIap.getProducts to return before calling RNIap.requestPurchase. We call RNIap.getProducts as soon as the app opens to avoid this, but that call has taken up to 11.5 days to return (It took  999,286,298 milliseconds once based on Date.now() before and after the 'await RNIap.getProducts' line). Also note that I think it can take a long time for purchaseErrorListener and/or purchaseUpdatedListener to execute. I found a recent case where the user got the successful purchase email, but we got an E_USER_CANCELLED error. In that case, the RNIap.getProducts only took 35 milliseconds, but finished 3 minutes after the RNIap.requestPurchase because RNIap.getProducts has to be called after the listeners are set up (if I remember correctly).

**Comment by manuel-grondona** [comment]
> **RNIap.getProducts has to be called after the listeners are set up**

Just to be sure, is this how it has to be? Couldn't find anything that said this or the opposite, hoewever, right now I'm doing it in the opposite order (getProducts is called before the listeners are setup), I believe it's working but would like to know if there could be a problem with the way I implemented it.

Thank you!

**Comment by cumom** [comment]
There could have been updates to fix this. But I was able to reproduce the
error on successful transactions. It could depend on how long it takes for
getProducts to return.

**Comment by manuel-grondona** [comment]
@cumom Thank you for your answer! In my experience, I'm using `getSubscriptions()` and I actually use the response to map through the different subscriptions to generate the purchase buttons, so if I don't have the response, I don't have buttons. So far I haven't had any delay problems with that method, but I do call it before setting up the listeners, so that is why I was asking about that process. Either way, I feel some laggy behavior, but it could be the way I'm implementing things..
