### ISSUE TITLE
requestSubscription promise is not resolved

### ISSUE THREAD

**Issue by Strate** [dooboolab/react-native-iap#984]
### Version of react-native-iap
4.4.6

### Version of react-native
0.61.5

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
`requestSubscription` promise is resolved

### Actual behavior
`requestSubscription` promise never resolved

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Just follow readme and try to request subscription

**Comment by hyochan** [comment]
We recommend this to be handled in `purchaseUpdated` event handler. Therefore, resolving this method seems quite useless but if this should be handled, I'll take a look.

**Comment by Jobeso** [comment]
@hyochan Resolving the promise would create a consistent api as `requestPurchase` is a promise as well that resolves. Additionally, this creates an easy implementation for showing a spinner while the user is purchasing. Using the purchase update listener for that would require a more complex architecture.
Thank you so much for your amazing work on this library!

**Comment by maxs15** [comment]
hyochan is correct, you must support support the purchaseUpdated event because if something fails the receipt could be triggered later, like when restarting the app.

Resolving a promise after the purchaseUpdated event is triggered (to make things easier like showing a spinner) is possible though, it is supported in [react-native-iaphub](https://github.com/iaphub/react-native-iaphub)

**Comment by marnusw** [comment]
I believe this is down to the same problem as #985. The promise does resolve in v4.4.3 of the library and the purchaseUpdated event fires, but in any later version (up to 4.4.8), neither happens.

**Comment by Jobeso** [comment]
Thanks for both of your replies.

@maxs15 of course there is a purchaseUpdated handler that handles the whole purchasing logic but since it is an event handler it is not bound to the component, so implementing the spinner with the event handler requires more effort, how much is depending on the app architecture.

@marnusw Could be related. I am running v4.4.3 and it is not working for me there either.

**Comment by alexpchin** [comment]
Does anyone have an example of how best to show a loading icon when purchasing? It seems quite complex to do this in the purchaseUpdateSubscription?

**Comment by alexpchin** [comment]
Any update on how best to show a loader whilst waiting for the purchase to complete?
